name: auto-pull-master

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      run: echo "hello"

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Pull latest changes on server
      run: |
        ssh -o StrictHostKeyChecking=no xrdpuser@10.42.180.47 << 'EOF'
          cd Home/bot-repo/tsom-bot
          git pull origin master
          exit
        EOF
